# Site settings
title: Braid.io - Modify, Manage and Expose all your data from one place.
email: hello@getbraid.io
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:8080" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
navigation:
- text: Community
  url: '/community'
- text: Docs
  url: '/docs'
- text: Log in
  url: '/login'

# Build settings
markdown: kramdown
exclude: [sass]
permalinks: pretty
